kind: ConfigMap
apiVersion: v1
metadata:
  name: testmap
  labels:
    synator/sync: "yes"
  annotations:
    synator/exclude-namespaces: kube-system, kube-node-lease, kube-public, local-path-storage
data:
  foo: bar
